#' A UI module that return a box that contains the UI components to read a table
#'
#' @param id module id
#'
#' @return A shiny box object that contains the UI components to read a table
#' @rdname INTERNAL_box_read_table_ui
#' @keywords internal
#'
#' @importFrom shiny tagList fileInput fluidRow NS textInput numericInput checkboxInput actionButton
#' @importFrom shinydashboardPlus box
#' @importFrom DT dataTableOutput
#' @importFrom shinyjs disabled
#'
box_read_table_ui <- function(id) {
    tagList(
        box(
            title = bs3Tooltip(
              trigger = if(id == "input") "assayData" else "colData",
              tooltipText = if(id == "input"){
                "A data.frame or any object that can be coerce into a data.frame,\
                holding the quantitative assay. This data.frame is typically \
                generated by an identification and software such as Sage, \
                Proteome Discoverer, MaxQuant, ..." 
              } else {
                "A data.frame (or any object that can be coerce to a data.frame)\
                containing sample/column annotations, including a quantCols column. And \
                in multi-set case a runCol column"
              }
            ),
            status = "primary",
            width = 12,
            solidHeader = TRUE,
            collapsible = TRUE,
            fileInput(
                inputId = NS(id, "file"),
                label = NULL,
                accept = c(".csv", ".tsv")
            ),
            fluidRow(
                box(
                    title = "Preview",
                    status = "primary",
                    width = 8,
                    solidHeader = FALSE,
                    collapsible = TRUE,
                    DT::dataTableOutput(NS(id, "dt_table"))
                ),
                box(
                    title = "Settings",
                    status = "primary",
                    width = 4,
                    solidHeader = FALSE,
                    collapsible = TRUE,
                    id = NS(id, "parameters"),
                    selectInput(
                        inputId = NS(id, "sep"),
                        label = "Separator character",
                        choices = c(";", ",", "Tab" = "\t", "Space" = " "),
                        selected = ","
                    ),
                    textInput(
                        inputId = NS(id, "dec"),
                        label = "Decimal character",
                        value = "."
                    ),
                    textInput(
                        inputId = NS(id, "comment_char"),
                        label = "Comment character",
                        value = "#"
                    ),
                    numericInput(
                        inputId = NS(id, "skip"),
                        label = "Number of line to skip before reading data",
                        value = 0
                    ),
                    checkboxInput(
                        inputId = NS(id, "stringsAsFactors"),
                        label = "String as Factor",
                        value = FALSE
                    ),
                    disabled(
                        actionButton(
                            inputId = NS(id, "import_button"),
                            label = "Import",
                            width = "100%",
                            class = "load-button"
                        )
                    )
                )
            )
        )
    )
}
